#!/usr/bin/env python3
"""Generate the drawn maps in maps/: home in the middle, rooms in the header.

  area_30x40   40 x 30 ft with walls following the old lab scan
               (maps/hospital_map): a narrow side room upper/lower on each
               end, and two partition walls across the middle.
  open_floor   the real test area (20 x 20 ft), no interior walls, so
               paths are near-straight lines. Use it when the
               drawn walls don't exist on the floor you drive on: the robot
               would otherwise detour around invisible walls.

Each map lists its rooms as "# room: name x y" lines; voice_delivery_node and
the test scripts read them, so a map always carries its own room positions.
Edit MAPS and rerun.

Usage: python3 scripts/make_area_map.py [name] [--size W_FT H_FT]
"""

import sys
from pathlib import Path

RES = 0.05           # m per pixel
THICK = 0.10         # wall thickness, m
FT = 0.3048
MARGIN = 0.40        # base_controller clamp bounds: inside walls, body margin

MAPS = {
    'area_30x40': {
        'size_ft': (40, 30),   # x (robot forward at start) by y
        # Interior walls as (x0, y0, x1, y1) segments in metres (+y = left).
        'walls': [
            (-4.25, 1.30, -4.25, 4.575),   # left upper side room (room5)
            (-4.10, -4.575, -4.10, -2.05),  # left lower side room (room4)
            # Middle partitions leave a 3.2 m opening at home: the arcs-only
            # base needs ~1.1 m to U-turn (a 1.6 m gap put it into a wall end).
            (-4.10, -0.30, -1.60, -0.30),  # middle partition, left part
            (1.60, 0.10, 4.15, 0.10),      # middle partition, right part
            (3.95, 1.95, 3.95, 4.575),     # right upper side room (room1)
            (4.20, -4.575, 4.20, -1.35),   # right lower side room
        ],
        'rooms': {
            'home': (0.00, 0.00),
            'room1': (5.00, 3.00),    # right upper side room
            'room2': (-1.50, -2.00),  # lower hall, left of centre
            'room3': (-1.50, 1.50),   # upper hall, left of centre
            'room4': (-5.10, -3.20),  # left lower side room
            'room5': (-5.10, 3.00),   # left upper side room
        },
    },
    'open_floor': {
        # The test area: 20 x 20 ft, robot in the middle facing +x. Three
        # rooms ~1.5 m (5 ft) out, spread in a triangle so every trip has
        # open space for the forward-only turn-around loops.
        'size_ft': (20, 20),
        'walls': [],
        'rooms': {
            'home': (0.00, 0.00),
            'room1': (1.50, 0.00),    # straight ahead
            'room2': (-0.75, 1.30),   # back left
            'room3': (-0.75, -1.30),  # back right
        },
    },
}

ROOT = Path(__file__).resolve().parent.parent


def write_map(name, spec):
    width, height = spec['size_ft'][0] * FT, spec['size_ft'][1] * FT
    w, h = round(width / RES), round(height / RES)
    ox, oy = -w * RES / 2, -h * RES / 2
    wall_px = round(THICK / RES)
    grid = [[254] * w for _ in range(h)]   # row 0 = top of the image

    def fill(x0, y0, x1, y1):
        """Occupy a wall segment, THICK wide, on whole pixels."""
        half = THICK / 2
        xa, xb = sorted((x0, x1))
        ya, yb = sorted((y0, y1))
        c0, c1 = round((xa - half - ox) / RES), round((xb + half - ox) / RES)
        b0, b1 = round((ya - half - oy) / RES), round((yb + half - oy) / RES)
        for b in range(max(b0, 0), min(b1, h)):
            for col in range(max(c0, 0), min(c1, w)):
                grid[h - 1 - b][col] = 0   # b counts up from the bottom row

    for row in range(h):
        for col in range(w):
            if (col < wall_px or row < wall_px
                    or col >= w - wall_px or row >= h - wall_px):
                grid[row][col] = 0
    for wall in spec['walls']:
        fill(*wall)

    bx, by = round(w * RES / 2 - MARGIN, 2), round(h * RES / 2 - MARGIN, 2)
    hx, hy = spec['rooms']['home']
    maps = ROOT / 'maps'
    ft = '%d x %d ft' % spec['size_ft']
    pgm = b'P5\n# %s drawn area (scripts/make_area_map.py)\n%d %d\n255\n' % (
        ft.encode(), w, h)
    (maps / f'{name}.pgm').write_bytes(pgm + bytes(v for r in grid for v in r))
    rooms = ''.join(f'# room: {r} {x:.2f} {y:.2f}\n' for r, (x, y) in spec['rooms'].items())
    (maps / f'{name}.yaml').write_text(
        f'# {ft} drawn area ({w * RES:.2f} x {h * RES:.2f} m), centre = (0, 0).\n'
        '# Generated by scripts/make_area_map.py; edit MAPS there, not here.\n'
        '# Robot starts in the MIDDLE facing +x (along the first size).\n'
        '# Read by start.sh and voice_delivery_node:\n'
        '# localization: static\n'
        f'# home: {hx} {hy}\n'
        f'# bounds: {-bx} {bx} {-by} {by}\n'
        f'{rooms}'
        f'image: {name}.pgm\n'
        'mode: trinary\n'
        f'resolution: {RES}\n'
        f'origin: [{ox:.3f}, {oy:.3f}, 0]\n'
        'negate: 0\n'
        'occupied_thresh: 0.65\n'
        'free_thresh: 0.25\n')
    print(f'Wrote maps/{name}.pgm/.yaml ({w} x {h} px, {len(spec["walls"])} interior '
          f'walls, {len(spec["rooms"])} rooms)')


def main():
    args = sys.argv[1:]
    if '--size' in args:
        i = args.index('--size')
        size = (int(args[i + 1]), int(args[i + 2]))
        del args[i:i + 3]
        for name in args or ['open_floor']:
            MAPS[name]['size_ft'] = size
    for name in args or MAPS:
        write_map(name, MAPS[name])


if __name__ == '__main__':
    main()
